### ISSUE TITLE
Multiple plot updates on region change

### ISSUE THREAD

**Issue by Tandethsquire** [Tandethsquire/CovidShiny#1]
Changing the region updates the 'intervention strength' parameter to be the mean of the fitted strength parameter. This update occurs in the server function, which causes two plot calls to be made.

Current workaround: force user to explicitly request a re-plot. It would be nice to have a better way to do this.

**Comment by jbadham** [comment]
I have a lot of my shiny functions start something like:

 ```
 commoncount <- reactive({
    df <- inData()                 # updates if input file changes
    df <- arrange(df, Person, Topic, Group)
   ...
```

In this case, the function named commoncount  is triggered if the variable inData is changed. So I keep the monitor of whether it is changed in a separate step than actually using it. I am not sure if this helps, but it is likely that the structure of the reactive links is the problem - I couldn't see where the code actually implements the specific plots you mean.

**Comment by Tandethsquire** [comment]
Thanks - Rachel found a fix using isolate() and some slightly neater code than I had previously!
